### ISSUE TITLE
Unable to Add Vendor Self Service Portal 

### ISSUE THREAD

**Issue by Sam58888** [Factory-Wheel-Warehouse/employee-portal#1] opened 2023-04-06 02:55 UTC
When a vendor is added in self service portal and updated . Vendor is deleted from dynamo db table. Its not saving the updated information

**Comment by dannygcordobap** [comment] 2023-04-06 13:11
## Overview

Vendor addition works and vendor data is appended to DynamoDB table successfully, but on update vendor addition is failing while deletion succeeds. 

Currently vendor update process flow is as follows:
- Delete previous vendor using vendor_name primary key
- Put modified vendor in DB as a new vendor

## Notes
1. The error seems to be occurring somewhere in the vendor "re-addition" portion of the process. 
2. On save the developer console reveals an invalid process resolution (see "Console Error" below)
3. Initially vendor saving wasn't working either. This was attributed to the `form` tag that was attempted to be used for validation and remained an artifact. This resulted in form query parameters being appended to the URL, presumably modifying subsequent vendor addition requests and causing them to fail. The issue was resolved on `form` tag removal in [the following commit](https://github.com/Factory-Wheel-Warehouse/employee-portal/commit/069aaff6c9852a0222d0b26270876ce5da5f69f1).

### Console Error
```
Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at e (aws.js:19:12)
    at aws.js:40:20
    at l (regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (regeneratorRuntime.js:125:22)
    at Generator.next (regeneratorRuntime.js:69:21)
    at Ue (asyncToGenerator.js:3:20)
    at i (asyncToGenerator.js:22:9)
    at asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
```

**Comment by dannygcordobap** [comment] 2023-04-06 17:54
Bug was caused by missing parameter to `updateVendors` call in the `onSaveHandler` function in the `VendorForm.jsx` component file. This has been resolved with [the following commit](https://github.com/Factory-Wheel-Warehouse/employee-portal/commit/98e3462e1efdff106cb678fad4ec6fa60d9c7a8e)

**Closed as completed** 2023-04-06 18:20 UTC
